name: main
on: [push]
jobs:
  check-image-changed:
    runs-on: ubuntu-latest
    outputs:
      image_changed: ${{ steps.check-image-changed.outputs.image-changed}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check changed
        run: |
          git diff --quiet --exit-code HEAD^ HEAD \
            dockerfiles/ros-humble/Dockerfile
          echo "::set-output name=image-changed::$?"
  build-image:
    runs-on: ubuntu-latest
    needs: [check-image-changed]
    if: needs.check-image-changed.outputs.image-changed == '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          docker build -t ghcr.io/thierry-martinez/ros-humble \
            dockerfiles/ros-humble
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.packages_write }}
      - name: Push
        run: |
          docker push ghcr.io/thierry-martinez/ros-humble
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Preparing the environment
        run: |
          sudo curl -sSL \
            https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
            -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt upgrade --yes
          sudo DEBIAN_FRONTEND=noninteractive apt install --yes ros-humble-ros-base ros-humble-demo-nodes-{cpp,py}
      - name: Talker/listener example
        run: |
          . /opt/ros/humble/setup.sh
          ros2 run demo_nodes_cpp talker &
          ros2 run demo_nodes_cpp listener &
          sleep 1 && killall ros2
