name: main
on: [push]
jobs:
  build image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.packages_write }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:dockerfiles/ros-humble"
          push: true
          tags: ghcr.io/thierry-martinez/ros-humble
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Preparing the environment
        run: |
          sudo curl -sSL \
            https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
            -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt upgrade --yes
          sudo DEBIAN_FRONTEND=noninteractive apt install --yes ros-humble-ros-base ros-humble-demo-nodes-{cpp,py}
      - name: Talker/listener example
        run: |
          . /opt/ros/humble/setup.sh
          ros2 run demo_nodes_cpp talker &
          ros2 run demo_nodes_cpp listener &
          sleep 1 && killall ros2
