name: main
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Preparing the environment
        run: |
          sudo add-apt-repository universe
          sudo curl -sSL \
            https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
            -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install ros-humble-ros-base
      - name: Talker/listener example
        run: |
          . /opt/ros/humble/setup.sh
          ros2 run demo_nodes_cpp talker &
          ros2 run demo_nodes_cpp listener &
          sleep 1000 && killall ros2
